<?php
declare(strict_types=1);
namespace PinVandaag\PMarketAPIDevelop\Model;
final class ApkInfo
{
    public function __construct(
        public int|string|null $apkId = null,
        public ?string $apkType = null,
        public ?string $apkIconFileId = null,
        public ?string $displayFileSize = null,
        public ?string $versionName = null,
        public ?bool $allowUpdateParamTemplate = null,
        public ?bool $allowUploadLocalParameter = null,
        public ?bool $allowParamPartialPush = null,
        public array $paramTemplateNameList = [],
        public array $apkCategoryList = [],
        public array $apkModelList = [],
        public array $apkModelNameList = [],
        public ?string $signatureProvider = null,
        public ?string $minSdkVersion = null,
        public array $apkFileFactoryList = [],
        public ?string $appName = null,
        public ?string $shortDesc = null,
        public ?string $description = null,
        public ?string $releaseNotes = null,
        public ?string $featuredImg = null,
        public ?string $accessUrl = null,
        public ?string $attachment = null,
        public ?string $attachmentName = null,
        public int|string|null $appId = null,
        public ?string $packageName = null,
        public ?float $price = null,
        public ?string $currency = null,
        public ?int $chargeType = null,
        public ?int $freeTrialDay = null,
        public ?string $osType = null,
        public ?string $appType = null,
        public ?bool $disableApkTypeChange = null,
        public ?bool $isFirstApkVersion = null,
        public ?string $chargeMode = null,
        public int|string|null $versionCode = null,
        public ?string $status = null,
        public ?string $screenshot0 = null,
        public ?string $screenshot1 = null,
        public ?string $screenshot2 = null,
        public ?string $screenshot3 = null,
        public ?string $screenshot4 = null,
    ) {}
}
